In [10]:
import pandas as pd
import numpy as np

In [11]:
l = [1,2,3,4]

In [12]:
a = np.array(l)

In [27]:
type(a)

numpy.ndarray

In [28]:
a.mean

<function ndarray.mean>

In [13]:
a.mean()

2.5

In [14]:
a.std()

1.118033988749895

In [18]:
a*2

array([2, 4, 6, 8])

In [19]:
a+1

array([2, 3, 4, 5])

In [20]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b



array([False,  True, False,  True])

In [21]:
a > b

array([False, False,  True, False])

In [26]:
a + b

array([5, 4, 5, 8])

In [29]:
a > 2

array([False, False,  True,  True])

In [30]:
a[a>2]

array([3, 4])

In [32]:
a[a==1]

array([1])

In [5]:
l = [1,2,3, 5]

In [6]:
l[:-2]

[1, 2]

In [7]:
l[-2:]

[3, 5]

In [9]:
assert 1 == 2

AssertionError: 

In [23]:
def add(i, j):
    assert type(i) == int, "not an int sorry"
    assert type(j) == int, "not an int dude"
    res = i + j
    assert type(res) == int
    return res

In [25]:
add(1,2)

3